# repository-stable - .github/workflows/stable.yml
name: Stable Reusable Workflow

on:
  workflow_call:  # This allows the workflow to be called from another workflow
    inputs:
      message:
        required: true
        type: string

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print the provided message
        run: echo "Message from reusable workflow: ${{ inputs.message }}"
